name: Run Command on Commit

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  run_command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run command on commit
      run: |
        if [[ $(git log -1 --pretty=%B) =~ "build" ]]; then
          ts-node ./src/generate/runCmd.ts
        fi
